name: pusher_beams
description: A new flutter plugin project.
version: 0.0.1
repository: https://github.com/pusher/flutter_pusher_beams/tree/master/
issue_tracker: https://github.com/pusher/flutter_pusher_beams/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+web%22

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  pusher_beams_platform_interface:
    git:
      url: git://github.com/mehrdad-shokri/flutter_pusher_beams
      path: packages/pusher_beams_platform_interface
      ref: develop
  pusher_beams_web:
    git:
      url: git://github.com/mehrdad-shokri/flutter_pusher_beams
      path: packages/pusher_beams_web
      ref: develop
  pusher_beams_android:
    git:
      url: git://github.com/mehrdad-shokri/flutter_pusher_beams
      path: packages/pusher_beams_android
      ref: develop
  pusher_beams_ios:
    git:
      url: git://github.com/mehrdad-shokri/flutter_pusher_beams
      path: packages/pusher_beams_ios
      ref: develop
  uuid: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mockito: ^5.0.16

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        default_package: pusher_beams_android
      ios:
        default_package: pusher_beams_ios
      web:
        default_package: pusher_beams_web

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
